
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vydlyvskhokxqxingjbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5ZGx5dnNraG9reHF4aW5namJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MzY3MzEsImV4cCI6MjA2MjIxMjczMX0.mNuZDOukJA-O3ecY5a_rVKQCeE74RqNrMEsdMEWCnzk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
